#!/bin/sh
# скрипт для самотестирования утилит pfs
# пока основные только
PFSLOAD=false
PFSUNLOAD=false
PFSRAMLOAD=false
PFSREBUILD=false
PFSMERGE=false

ex(){ printf "$m" ; exit 1 ; }
mkdir -p ./first/111 ./second/222
: > ./first/111/file
: > ./second/222/file
mkpfs ./first && mkpfs ./second && MKPFS=OK
m="mkpfs=			$MKPFS" 
rm -rf ./first
rm -rf ./second
[ "$MKPFS" != "OK" ] && ex

pfsmerge ./first.pfs ./second.pfs testmodule.pfs && PFSMERGE=OK
m="\n=============\n$m\npfsmerge=		$PFSMERGE" ; [ "$PFSMERGE" != "OK" ] && ex
rm -f ./first.pfs
rm -f  ./second.pfs

pfsextract testmodule.pfs && [ -f testmodule_pfs/first.pfs ] &&
    [ -f testmodule_pfs/second.pfs ]  && PFSEXTRACT=OK || ex
m="\n=============\n$m\npfsextract=<---><------>$PFSEXTRACT"
rm -r testmodule_pfs

pfsload ./testmodule.pfs && PFSLOAD=OK
m="$m\npfsload=		$PFSLOAD" ; [ "$PFSLOAD" != "OK" ] && exit

pfsunload ./testmodule.pfs && PFSUNLOAD=OK
m="$m\npfsunload=		$PFSUNLOAD" ; [ "$PFSUNLOAD" != "OK" ] && ex

pfsramload ./testmodule.pfs && PFSRAMLOAD=OK
m="$m\npfsramload=		$PFSRAMLOAD" ; [ "$PFSRAMLOAD" != "OK" ] && ex

rm -f ./testmodule.pfs

pfsrebuild testmodule.pfs && PFSREBUILD=OK
m="$m\npfsrebuild=		$PFSREBUILD" ; [ "$PFSREBUILD" != "OK" ] && ex

pfsunload ./testmodule.pfs
rm -f ./first.pfs
rm -f  ./second.pfs
rm -f testmodule.pfs
printf "$m\n==== all OK\n"
