#!/bin/sh
#Uninstall .pfs (for PuppyRus), by Zay, GPL v3.
#Version 0.9
#Modify 28.12.2013

if [ ! "$1" ]; then
  echo "Usage: $(basename "$0") PACKAGE" >&2; exit 1
fi

fileslist="/etc/packages/install/$1/pfs.files"
if [ -f "${fileslist}" ]; then 
  if [ -d "/tmp/.pfs/uninstall/$1" ]; then
    echo "Progress is already running!" >&2; exit 1    
  fi
  mkdir -p "/tmp/.pfs/uninstall/$1"
  mv "${fileslist}" "/tmp/.pfs/uninstall/$1"
  rm -rf "/etc/packages/install/$1/" 
  finded="$(find /etc/packages/ -mindepth 3 -maxdepth 3 -type f -name 'pfs.files' | while read listfiles; do cat "${listfiles}" | sed -e 's:[\]:\\\\\\\\:g'; done)"
  listfiles="$(cat "/tmp/.pfs/uninstall/$1/pfs.files" | sed -e 's:^[^/]*::' -e 's:[\]:\\\\:g')"
  echo "${listfiles}" | while read file; do echo "${finded}" | grep -q -F "${file}" || rm -f "${file}" 2>/dev/null; done
  echo "${listfiles}" | grep -q -F "/lib/modules" && depmod &
  [ ! -z "$(which ldconfig)" ] && echo "${listfiles}" | grep -q -F "/lib" && ldconfig &
  echo "${listfiles}" | grep -q -F "/usr/share/glib-2.0/schemas" && glib-compile-schemas /usr/share/glib-2.0/schemas/ &
  rm -rf "/tmp/.pfs/uninstall/$1"
else
  echo "Package \"$1\" is not installed!" >&2; exit 1
fi
sync

exit 0
