#!/bin/bash
#Update VERSION tag in all pfs-utils files
#$1 - Version
#Default -  current Version value plus one (in minor section)

[ $1 ] && ver=$1
if ! [ $ver ] ; then
	current=$(cat ../project-files/usr/bin/pfsload |grep 'VERSION' |awk '{print $2}')
	major=$(echo $current |awk -F. '{print $1}')
	minor=$(echo $current |awk -F. '{print $2}')
	ver=${major}.$(echo $(($minor +1)))
fi
filelist="$(find ../project-files -type f) ../VERSION.md"
for file in  $filelist ;do
	sed -i "s|VERSION\ *[:digit:]*.*|VERSION\ $ver|" $file
done
echo VERSION udated to $ver

