#!/bin/bash
#Update VERSION tag in all pfs-utils files
#$1 - Version
#Default -  current Version value plus one (in minor section)
[ $1 ] && ver=$1
if ! [ $ver ] ; then
	current=$(cat ../project-files/usr/bin/pfsload |grep 'VERSION')
	major=$(echo $current |awk -F. '{print $1}')
	minor=$(echo $current |awk -F. '{print $2}')
	ver=${major}.$(echo $(($minor +1)))
fi
for file in $(find ../project-files -type f) ;do
	sed -i "s|#VERSION\ *[:digit:]*.*|#VERSION\ $ver|" $file
done
echo VERSION tag udated to $ver

