#!/bin/sh
#Install .pet (for PuppyRus), by Zay, GPL v3.
#Version 0.8
#Modify 28.12.2013

if [ "$1" ]; then
  infile="$1"
else
  echo "Usage: $(basename "$0") FILE" >&2; exit 1
fi
if [ -f "${infile}" ]; then
  instfile="$(realpath "${infile}")"
else
  echo "File \"${infile}\" not found!" >&2; exit 1
fi

path="$(pwd)"
tmpdir="/tmp/.pfs/petinstall/$(basename "${instfile}")"

if [ -d "${tmpdir}" ]; then
  rmdir "${tmpdir}" 2>/dev/null
  if [ -d "${tmpdir}" ]; then
    echo "Progress is already running!" >&2; exit 1    
  fi
fi

mkdir -p "${tmpdir}"
cp -af "${instfile}" "${tmpdir}"
status=$?
instpet="${tmpdir}/$(basename "${instfile}")"
basepack="$(basename "${instpet}" .pet)"
  
if [ ${status} -eq 0 ]; then 
  tar xzf "${instpet}" -C "${tmpdir}" >/dev/null 2>&1
  status=$?
  if [ ${status} -ne 0 ]; then    
    truncate `stat --format=%s "${instpet}" | expr $(cat) - 32` "${instpet}" >/dev/null 2>&1
    status=$?
    if [ ${status} -eq 0 ]; then
      tar xzf "${instpet}" -C "${tmpdir}" >/dev/null 2>&1
      status=$?
    fi
  fi
fi
rm -f "${instpet}" >/dev/null 2>&1

if [ ${status} -eq 0 ]; then
  if [ -d "${tmpdir}/${basepack}" ]; then
    pfsname="${basepack}_pet"
    mkdir -p "${tmpdir}/${basepack}/etc/packages/install/${pfsname}"
    cd "${tmpdir}/${basepack}"
    status=$?
  else
    status=1
  fi
fi

if [ ${status} -eq 0 ]; then
  [ "$(pwd)" != "/" ] && find "./etc/packages/install/" -mindepth 1 -maxdepth 1 -type d ! -name "${pfsname}" -exec rm -rf "{}" \;
  mkdir -p "./etc/packages/install/${pfsname}"
  [ -f "./etc/packages/install/${pfsname}/pfs.files" ] && rm -f "./etc/packages/install/${pfsname}/pfs.files"
  [ -f "./etc/packages/install/${pfsname}/pfs.dirs.empty" ] && rm -f "./etc/packages/install/${pfsname}/pfs.dirs.empty"
  [ ! -f "./etc/packages/install/${pfsname}/pfs.specs" ] && echo "name=\"${pfsname}\"" >"./etc/packages/install/${pfsname}/pfs.specs"
  find . -mindepth 1 -maxdepth 1 -type f -name "*pet*specs*" | while read specs
  do
    mv "${specs}" "./etc/packages/install/${pfsname}/"
  done
  echo "$(find . ! -type d | cut -f2- -d'.' | grep -v -F '/etc/packages/' | sort -f)" >"./etc/packages/install/${pfsname}/pfs.files"
  dirsempty="$(find . -type d -empty | cut -f2- -d'.' | sort -f)" 
  dirsfile="./etc/packages/install/${pfsname}/pfs.dirs.empty"
  [ "${dirsempty}" = "" ] && [ -f "${dirsfile}" ] && rm -f "${dirsfile}"
  [ "${dirsempty}" != "" ] && echo "${dirsempty}" >"${dirsfile}"
fi

cd "${path}"

if [ ${status} -eq 0 ]; then
  listpackage=""
  for arg in "$@"
  do
    case "${arg}" in 
      "-l" | "--lower") insmode="lower";;
      "-u" | "--upper") ;;
    esac
  done
  pack="${tmpdir}/${basepack}/etc/packages/install/${pfsname}"
fi

if [ ${status} -eq 0 ]; then
  if [ -f "${pack}/pfs.files" ]; then
    if [ -f "${pack}/pfs.dirs.empty" ]; then
      cat "${pack}/pfs.dirs.empty" | while read dirempty
      do
        mkdir -p "${dirempty}"
      done
    fi
    cat "${pack}/pfs.files" | while read file
    do
      cpnamedir="$(dirname "${file}")"
      mkdir -p "${cpnamedir}"
      if [ "${insmode}" != "lower" ];then
        mv -f "${tmpdir}/${basepack}${file}" "${cpnamedir}"
      else
        [ ! -e "${file}" ] && mv -f "${tmpdir}/${basepack}${file}" "${cpnamedir}"
      fi
      status=$?
      if [ ${status} -gt 0 ]; then
        echo "Install error!" >&2; break
      fi
    done
    mkdir -p "/etc/packages/install"      
    [ -d "/etc/packages/install/${pfsname}/" ] && rm -rf "/etc/packages/install/${pfsname}/"
    mv -f "${tmpdir}/${basepack}/etc/packages/install/${pfsname}" "/etc/packages/install"
    status=$?
    if [ ${status} -gt 0 ]; then
      echo "Install error!" >&2; break
    fi
  fi
fi

if [ ${status} -eq 0 ]; then
  [ `find "${pack}/lib/modules/$(uname -r)" 2>/dev/null | grep -ic "ko$"` -gt 0 ] && depmod
  [ ! -z "$(which ldconfig)" ] && [ -d "${tmpdir}/${basepack}/usr/lib" -o -d "${tmpdir}/${basepack}/usr/local/lib" ] && ldconfig
fi

rm -rf "/tmp/.pfs/petinstall/$(basename "${instfile}")"

[ ${status} -eq 0 ] && sync || echo "Install error!" >&2

exit ${status}
