#!/bin/ash
#151129 sfs

J(){
pidof menu-dmn || menu-dmn start & 
exit
}
pidof jwm >/dev/null && J

rm "/home/`sfsusr`/.cache/menus/"* 2>/dev/null
killall menu-cached 2>/dev/null && exit

sudo -u $(sfsusr) sh -c "
       $(ps -C xfdesktop ewwww --no-headers \
         |sed -n 's/^.* \(xfdesktop\) \(.*\)$/\2 \1 -R/p')
       $(ps -C xfce4-panel ewwww --no-headers \
         |sed -n 's/^.* \(xfce4-panel\) \(.*\)$/\2 \1 -r/p')"