#!/bin/ash
#151129 sfs

J(){
pidof menu-dmn || menu-dmn start & 
exit
}
pidof jwm >/dev/null && J

rm "/home/`sfsusr`/.cache/menus/"* 2>/dev/null
killall menu-cached && exit

pidof xfdesktop >/dev/null && xfdesktop -R
