#!/bin/bash
# Просмотр списка пакетов PFS (PuppyRus), by Zay, GPL v3.
# Версия 0.6, последнее изменение: 16.01.2013

export DIALOG_INFO="<window title=\"$1\" resizable=\"false\">
<vbox border-width=\"16\"><text><label>\" Подготовка списка пакетов... \"</label></text></vbox>
</window>"
gtkdialog3 --program=DIALOG_INFO --center &
dlgwait=$!

# Чтение списка пакетов:
if [ -f /tmp/permanent_pfs_load.log ]; then
  permanentpacks="`cat /tmp/permanent_pfs_load.log | tr ' ' '_' | while read pfile
  do
    if [ -d "/mnt/.${pfile}/etc/packages/mount" ]; then
      echo "$(find /mnt/.${pfile}/etc/packages/mount -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null | sort -f )"              
    fi
  done | sort -u`"
fi

allmountpacks="$(find /etc/packages/mount -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null | sort -f)"
mountpacks="$(echo "${allmountpacks}${IFS}${permanentpacks}${IFS}" | sort | uniq -u)"

[ -d "/etc/packages/install" ] && installpacks="$(find /etc/packages/install -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null | sort -f | grep . | sed 's/^/<item>/;s/$/<\/item>/')"

# Подготовка главного окна:
export MAIN_DIALOG="<window title=\" Пакеты в системе \">
<hbox homogeneous=\"true\">
 <tree selection-mode=\"0\">
  <label>Постоянно подключённые пакеты</label>
  <height>380</height>
  <width>260</width>
  $(echo "${permanentpacks}" | grep . | sed 's/^/<item>/;s/$/<\/item>/')
 </tree>
 <tree selection-mode=\"0\">
  <label>Временно подключённые пакеты</label>
  <height>380</height>
  <width>260</width>
  $(echo "${mountpacks}" | grep . | sed 's/^/<item>/;s/$/<\/item>/')
 </tree>
 <tree selection-mode=\"0\">
  <label>Установленные пакеты</label>
  <height>380</height>
  <width>260</width>
  ${installpacks}
 </tree>
</hbox>
</window>"

kill ${dlgwait} 2>/dev/null
gtkdialog3 --program=MAIN_DIALOG --center &
exit
