#!/bin/bash
# Установка PET-пакета или конвертация его в PFS (PuppyRus), by Zay, GPL v3.
# Версия 0.5, последнее изменение: 09.12.2012

[ ! "$1" ] && exit 1

export MAIN_DIALOG="<window title=\" PET-пакет \" resizable=\"false\">
 <vbox border-width=\"3\">
  <frame  Выберите действие: >
   <vbox border-width=\"5\">
    <button>
     <label>\"   Установить пакет в систему  \"</label>
     <action type=\"exit\">INSTALL</action>
    </button>
    <button>
     <label>\"   Конвертировать PET в PFS   \"</label>
     <action type=\"exit\">CONVERT</action>
    </button>
   </vbox>
  </frame>
 </vbox>
</window>"

REST="`gtkdialog3 --program=MAIN_DIALOG --center`"

eval "$REST"
case "${EXIT}" in
  "INSTALL") 
  
    export WAIT_DIALOG="<window title=\" Установка... \" resizable=\"false\"><vbox border-width=\"16\">
    <text><label>\"Пакет устанавливается.${IFS}Пожалуйста, подождите...\"</label></text>
    </vbox></window>"
    gtkdialog3 --program=WAIT_DIALOG --center &
    dlgwait=$!
    
    petinstall "$1"
    status=$?
    
    if [ ${status} -eq 0 ]; then
      fixmenus
      mfs="$(which mkfontscale)"
      mfd="$(which mkfontdir)"
      for fontdir in "/usr/X11R6/lib/X11/fonts/TTF" "/usr/share/fonts/default/TTF"
      do
        cd "${fontdir}"
        [ "${mfs}" !=  "" ] && "${mfs}" .
        [ "${mfd}" !=  "" ] && "${mfd}" .	
      done
    fi  
    kill ${dlgwait} 2>/dev/null
    
    if [ ${status} -eq 0 ]; then
      Xdialog --title " Установка PET " --msgbox " Пакет успешно установлен! \n" 6 0
    else
      export ERROR_DIALOG="<window title=\" Ошибка! \" resizable=\"false\" icon-name=\"gtk-stop\">
      <vbox>
       <vbox border-width=\"12\"><hbox>
        <pixmap icon_size=\"3\"><input file stock=\"gtk-stop\"></input></pixmap>
        <text><label>\"  При установке пакета произошла ошибка! \"</label></text>
       </hbox></vbox>
       <hbox homogeneous=\"true\"><button ok></button></hbox>
      </vbox>
      </window>"
      gtkdialog3 --program=ERROR_DIALOG --center &
    fi
    ;;
    
  "CONVERT")
  
    export WAIT_DIALOG="<window title=\" PET > PFS ... \" resizable=\"false\"><vbox border-width=\"16\">
    <text><label>\"Пожалуйста, подождите...\"</label></text>
    </vbox></window>"
    gtkdialog3 --program=WAIT_DIALOG --center &
    dlgwait=$!
    
    pet2pfs "$1" -no-progress
    status=$?
    
    kill ${dlgwait} 2>/dev/null
    if [ ${status} -eq 0 ]; then
      Xdialog --title " PET " --msgbox " Файл \"$(basename "$1" .pet).pfs\" успешно создан! \n" 6 0
    else
      export ERROR_DIALOG="<window title=\" Ошибка! \" resizable=\"false\" icon-name=\"gtk-stop\">
      <vbox>
       <vbox border-width=\"12\"><hbox>
        <pixmap icon_size=\"3\"><input file stock=\"gtk-stop\"></input></pixmap>
        <text><label>\"  Не удалось создать PFS-пакет! \"</label></text>
       </hbox></vbox>
       <hbox homogeneous=\"true\"><button ok></button></hbox>
      </vbox>
      </window>"
      gtkdialog3 --program=ERROR_DIALOG --center &
    fi
    ;;
esac

exit
