#!/bin/sh
#Install .pfs (for PuppyRus), by Zay, GPL v3.
#Version 0.12
#Modify 28.12.2013

if [ "$1" ]; then
  instfile="$1"
else
  echo "Usage: $(basename "$0") FILE"; exit 1
fi
if [ ! -f "${instfile}" ]; then
  echo "File \"${instfile}\" not found!" >&2; exit 1
fi
status=0

bsname="$(basename "${instfile}")"
if [ -d "/tmp/.pfs/install/${bsname}" ]; then
  rmdir "/tmp/.pfs/install/${bsname}" 2>/dev/null
  if [ -d "/tmp/.pfs/install/${bsname}" ]; then
    echo "Progress is already running!" >&2; exit 1
  fi
fi
mkdir -p "/tmp/.pfs/install/${bsname}"

listpackage=""
for arg in "$@"
do
  case "${arg}" in 
    "-p" | "--packages" | "-up" | "-pu") upacklist="yes";;
    "-lp" | "-pl") upacklist="yes"; insmode="lower";;
    "-l" | "--lower") insmode="lower";;
    "-u" | "--upper") ;;
    "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2; exit 1;;
    *) [ "${upacklist}" = "yes" ] && listpackage="${listpackage}${arg}$IFS";;
  esac
done
[ "${listpackage}" = "" ] && listpackage="$(unsquashfs -l "${instfile}" 2>/dev/null | grep '/etc/packages/mount/' | cut -f5 -d'/' | sort -uf)"

allfiles="`echo "${listpackage}" | while read pack; do
  unsquashfs -l "${instfile}" 2>/dev/null | grep -q "/etc/packages/mount/${pack}/pfs.files"
  [ $? -gt 0 ] && continue
  unsquashfs -d "/tmp/.pfs/install/${bsname}/${pack}" "${instfile}" -ef "/etc/packages/mount/${pack}/pfs.files" -n >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    [ -f "/tmp/.pfs/install/${bsname}/${pack}/etc/packages/mount/${pack}/pfs.files" ] && cat "/tmp/.pfs/install/${bsname}/${pack}/etc/packages/mount/${pack}/pfs.files" 2>/dev/null | sed -e 's:^[^/]*::' -e 's:[\]:\\\\\\\\:g'
  fi
  rm -rf "/tmp/.pfs/install/${bsname}/${pack}" 2>/dev/null
  unsquashfs -l "${instfile}" 2>/dev/null | grep -q "/etc/packages/mount/${pack}/pfs.dirs.empty"
  [ $? -gt 0 ] && continue
  unsquashfs -d "/tmp/.pfs/install/${bsname}/${pack}" "${instfile}" -ef "/etc/packages/mount/${pack}/pfs.dirs.empty" -n >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    if [ -f "/tmp/.pfs/install/${bsname}/${pack}/etc/packages/mount/${pack}/pfs.dirs.empty" ]; then
      cat "/tmp/.pfs/install/${bsname}/${pack}/etc/packages/mount/${pack}/pfs.dirs.empty" 2>/dev/null | sed -e 's:^[^/]*::' -e 's:[\]:\\\\\\\\:g' -e 's:[/*]$::g' | while read dirempty; do mkdir -p "${dirempty}"; done
    fi
  fi
  rm -rf "/tmp/.pfs/install/${bsname}/${pack}" 2>/dev/null
  unsquashfs -d "/tmp/.pfs/install/${bsname}/${pack}" "${instfile}" -ef "/etc/packages/mount/${pack}" -n >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    if [ -d "/tmp/.pfs/install/${bsname}/${pack}/etc/packages/mount/${pack}" ]; then
      [ -d "/etc/packages/install/${pack}" ] && rm -rf "/etc/packages/install/${pack}"
      mkdir -p "/etc/packages/install" 
      cp -a "/tmp/.pfs/install/${bsname}/${pack}/etc/packages/mount/${pack}" "/etc/packages/install/${pack}"
    fi
  fi
  rm -rf "/tmp/.pfs/install/${bsname}/${pack}" 2>/dev/null
done`"

if [ "${allfiles}" != "" ]; then
  if echo "${allfiles}" | grep -q -F '\'; then
    unsquashfs -d "/tmp/.pfs/install/${bsname}/tmp" "${instfile}" >/dev/null 2>&1
    status=$?
    allunpack="yes"
  fi
  echo "${allfiles}" | grep . | while read file
  do
    if [ "${allunpack}" != "yes" ]; then
      unsquashfs -d "/tmp/.pfs/install/${bsname}/tmp" "${instfile}" -ef "$(echo "${file}" | sed -e 's/\[/\\\[/g')" -n >/dev/null 2>&1
      status=$?
    fi
    if [ ${status} -eq 0 ]; then    
      cpnamedir="$(dirname "${file}")"
      mkdir -p "${cpnamedir}"
      mv -f "/tmp/.pfs/install/${bsname}/tmp${file}" "${cpnamedir}"
      status=$?
    fi
    [ "${allunpack}" != "yes" ] && rm -rf "/tmp/.pfs/install/${bsname}/tmp" 2>/dev/null
    if [ ${status} -gt 0 ]; then
      exit ${status}
    fi
  done
  status=$?
fi

rm -rf "/tmp/.pfs/install/${bsname}" 2>/dev/null
[ ${status} -gt 0 ] && echo "Install error!" >&2

exit ${status}
