#!/bin/sh
#Mount filesystem to AUFS (for PuppyRus), by Zay, GPL v3.
#Version 0.21
#Modify 26.04.2015

for arg in "$@"
do
  case "${arg}" in
    "-u" | "--upper") mntmode="upper";;
    "-l" | "--lower") mntmode="lower";;
    "-n" | "--no-update") fupdate="no";;
    "-r" | "--read-only") romode="yes";;
    "-h" | "--help") infile=""; break;;
    "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2; exit 1;;
    *) infile="${arg}";;
  esac
done
if [ "${infile}" = "" ]; then
  echo "Usage: $(basename "$0") [OPTIONS] FILESYSTEM${IFS}${IFS}Options:"
  echo " -u, --upper    Mount filesystem to upper layer (AUFS)."
  echo " -l, --lower    Mount filesystem to lower layer (AUFS)."; exit
fi

if [ -f "${infile}" ]; then
  fsfile="$(realpath "${infile}")"
  devtype="file"
elif [ -b "${infile}" ]; then
  fsfile="${infile}"
  devtype="dev"
elif [ -d "${infile}" ]; then
  fsfile="$(realpath "${infile}")"
  devtype="dir"
else
  echo "Object \"${infile}\" not found!" >&2; exit 1
fi

if [ "${devtype}" != "dir" ]; then
  diskinfo="$(disktype "${fsfile}" 2>/dev/null)"
  fstype=$( echo "${diskinfo}" \
            |tr [:upper:] [:lower:] \
            |grep -oE "squashfs|ext[2-4]" )
else
  fsinfo="$(df -aT "${fsfile}" | tail -n 1 | tr -s ' ' '_' | cut -d'_' -f 2)"
  case "${fsinfo}" in
    "ext2"|"ext3"|"ext4"|"squashfs") fstype="${fsinfo}";;
  esac
fi
[ "${fstype}" = "" ] && echo "Filesystem not supported!" >&2 && exit 1

fsname="$(basename "${fsfile}")"
if [ "$(echo "${fsname##*.}" | tr A-Z a-z)" = "pfs" ]; then
  checksfsxz >/dev/null
  [ $? -gt 0 ] && echo "Kernel not support PFS!" >&2 && exit 1
fi
mountpoint="/mnt/.${fsname}"
[ -d "${mountpoint}" ] && rmdir "${mountpoint}" 2>/dev/null
[ -d "${mountpoint}" ] && echo "Object \"${fsfile}\" is mounted!" >&2 && exit 1

mkdir -p "${mountpoint}"
case "${devtype}" in
   "file" )   [ "${romode}" -o "${fstype}" == "squashfs" ] \
		&& optmnt="loop,ro" || optmnt="loop"
	      mountb -t ${fstype} -o ${optmnt} "${fsfile}" "${mountpoint}" ;;
    "dev" )   [ "${romode}" ] && optmnt="ro" || optmnt="rw"
              mountb -t ${fstype} -o ${optmnt} "${fsfile}" "${mountpoint}" ;;
    "dir" )   mountb -t ${fstype} --bind "${fsfile}" "${mountpoint}" ;;
esac 
[ $? -ne 0 ] && echo "Unable to mount \"${fsfile}\" in \"${mountpoint}\"." >&2 && exit 1

[ "${romode}" -o "${fstype}" == "squashfs" ] && optmnt="=rr+wh" || optmnt="=ro+wh"
if [ "${mntmode}" != "lower" ]; then
    aufslayer="$(topaufslayer 2>/dev/null)"
    case "${aufslayer}" in
      ''|*[!0-9]*) aufslayer=1;;
    esac
    mountb -o remount,add:${aufslayer}:"${mountpoint}${optmnt}" /
else
    mountb -o remount,append:"${mountpoint}${optmnt}" /
fi
if [ $? -ne 0 ]; then
    umountb -d "${mountpoint}"
    rmdir "${mountpoint}"
    echo "AUFS error!" >&2
    exit 1
fi

if [ "${fupdate}" != "no" ]; then
    pfs-update-caches "${mountpoint}"
fi
exit 0
