#!/bin/sh
#Copy to RAM & Mount SquashFS to AUFS (for PuppyRus), by «sfs» & Zay, GPL v3.
#Version 0.11
#Modify 28.12.2013

copyramdir="/tmp/.mountRAM"

for arg in "$@"
do
  case "${arg}" in
    "-u" | "--upper") mntmode="-u";;
    "-l" | "--lower") mntmode="-l";;
    "-n" | "--no-update") fupdate="-d";;
    "-r" | "--read-only") romode="-r";;
    "-h" | "--help") infile=""; break;;
    "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2; exit 1;;
    *) infile="${arg}";;
  esac
done
if [ "${infile}" = "" ]; then
  echo "Usage: $(basename "$0") [OPTIONS] FILE${IFS}${IFS}Options:"
  echo " -u, --upper    Copy file to RAM & Mount to upper layer (AUFS)."
  echo " -l, --lower    Copy file to RAM & Mount to lower layer (AUFS)."; exit
fi
if [ -f "${infile}" ]; then
  fsfile="$(realpath "${infile}")"
else
  echo "File \"${infile}\" not found!" >&2; exit 1
fi

fsname="$(basename "${fsfile}")"
mountpoint="/mnt/.${fsname}"
[ -d "${mountpoint}" ] && rmdir "${mountpoint}" 2>/dev/null
if [ -d "${mountpoint}" ]; then
  echo "File \"${fsname}\" is mounted!" >&2; exit 1
fi

freeram="$(checkramfree 2>/dev/null)"
case ${freeram} in
  ''|*[!0-9]*) freeram="$(free | grep 'Mem:' | tr -s ' ' | cut -f 4 -d ' ')";;
esac
filesize="`expr $(du -k "${fsfile}" | cut -f 1) + 1024`"
minram="$(expr ${filesize} \* 2)"
[ ${minram} -lt 131072 ] && minram=131072
[ ${minram} -lt ${freeram} ] && modecopy="yes" || modecopy="no"

if [ "${modecopy}" = "yes" ]; then
  if [ -d "${copyramdir}/${fsname}" ]; then
    busybox mount | grep -q -F "${copyramdir}/${fsname}"
    if [ $? -eq 0 ]; then
      losetup-FULL -a | grep -q -F "${copyramdir}/${fsname}"
      if [ $? -gt 0 ]; then
        busybox umount "${copyramdir}/${fsname}" >/dev/null 2>&1
        [ $? -eq 0 ] && rmdir "${copyramdir}/${fsname}" 2>/dev/null
      fi
    else
      rmdir "${copyramdir}/${fsname}" 2>/dev/null
    fi
    [ -d "${copyramdir}/${fsname}" ] && modecopy="no" 
  fi
fi

if [ "${modecopy}" = "yes" ]; then 
  sync
  mkdir -p "${copyramdir}/${fsname}"
  busybox mount -t tmpfs -o size=${filesize}k tmpfs "${copyramdir}/${fsname}" >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    sync
    echo "\"${fsname}\" copying to RAM..."
    cp -afL "${fsfile}" "${copyramdir}/${fsname}"
    if [ $? -gt 0 ]; then
      busybox umount "${copyramdir}/${fsname}" >/dev/null 2>&1
      rmdir "${copyramdir}/${fsname}" 2>/dev/null
      modecopy="no"
    fi
  else
    modecopy="no"
  fi
  sync
fi

if [ "${modecopy}" = "yes" ]; then
  pfsload ${mntmode} ${fupdate} ${romode} "${copyramdir}/${fsname}/${fsname}"
else
  pfsload ${mntmode} ${fupdate} ${romode} "${fsfile}" 
fi
status=$?

if [ ${status} -gt 0 ]; then
  echo -en "\\033[1;31m"; echo -n "ERROR copy to RAM!"; echo -en "\\033[0;39m"
  busybox umount "${copyramdir}/${fsname}" >/dev/null 2>&1
  rmdir "${copyramdir}/${fsname}" 2>/dev/null
fi

exit ${status}
