#!/bin/sh
#Free RAM, by «sfs» & Zay, GPL v3.
#Version 0.8
#Modify 28.12.2013

copyramdir="/tmp/.mountRAM"

if [ "$1" ]; then
  [ -f "$1" ] && fsname="`basename $(realpath "$1")`" || fsname="$(basename "$1")"
else
  if [ -d "${copyramdir}" ]; then
    useloop="$(losetup-FULL -a)"
    find "${copyramdir}" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | while read rampfsdir
    do
      echo "${useloop}" | grep -q -F "${rampfsdir}"
      [ $? -gt 0 ] && "$0" "$(basename "${rampfsdir}")"
    done
  fi
  exit
fi

if [ -d "${copyramdir}/${fsname}" ]; then
  busybox mount | grep -q -F "${copyramdir}/${fsname}"
  if [ $? -eq 0 ]; then
    losetup-FULL -a | grep -q -F "${copyramdir}/${fsname}"
    if [ $? -gt 0 ]; then
      busybox umount "${copyramdir}/${fsname}"
      if [ $? -eq 0 ]; then
        rmdir "${copyramdir}/${fsname}" 2>/dev/null
      else
        echo "ERROR free RAM!" >&2; exit 1
      fi
    fi
  else
    rmdir "${copyramdir}/${fsname}" 2>/dev/null
  fi
fi
  
exit 0
  