#!/bin/sh
#Unmount filesystem to AUFS (for PuppyRus), by Zay, GPL v3.
#Version 0.16
#Modify 26.04.2015

for arg in "$@"
do
  case "${arg}" in
    "-n" | "--no-update") fupdate="no";;
    "-h" | "--help") infile=""; break;;
    "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2; exit 1;;
    *) infile="${arg}";;
  esac
done
if [ "${infile}" = "" ]; then
  echo "Usage: $(basename "$0") FYLESYSTEM"; exit
fi

fsname="$(basename "${infile}")"
mountpoint="$(grep -ho "/.*${fsname}=r" /sys/fs/aufs/*/br[0-9]*)"
mountpoint="${mountpoint%=r}"

[ ! "${mountpoint}" ] \
    && echo "Object \"${fsname}\" not mounted in aufs." && exit 1

mountb -o remount,del:"${mountpoint}" /
[ $? -ne 0 ] && echo "Unable del ${mountpoint} from aufs" && exit 1

if [ "${fupdate}" != "no" ]; then
    pfs-update-caches "${mountpoint}"
fi

fsfile=$(grep "$mountpoint" /proc/mounts | cut -d' ' -f1)
echo "$fsfile" | grep -q "/dev/loop" \
  && { fsfile=$(losetupb "$fsfile" | cut -d' ' -f3)
       fsfile=${fsfile#(} ; fsfile=${fsfile%)}
      }

if [ "$fsfile" ] ; then
    umountb -d "${mountpoint}"
    [ $? -ne 0 ] && echo "Unmount \"${fsname}\" failed!" >&2
    rmdir "${mountpoint}" 2>/dev/null
else fsfile="${mountpoint}"
fi

[ "$(df -aT "$fsfile" | tail -n 1 | tr -s ' ' | cut -d' ' -f2)" == "tmpfs" ] \
  && rm -rf "$fsfile"